# -*- coding: utf-8 -*-
"""module_4_data_608.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wvu_tnYsim5fwhac-mE4iG-0OAl71IYK
"""

import pandas as pd
import numpy as np

"""# Dataset size"""

clean_url = ('https://data.cityofnewyork.us/resource/nwxe-4ae8.json?$limit=5&$offset=' + str(0) +\
        '&$select=count(tree_id)').replace(' ', '%20')
df_size = pd.read_json(clean_url)
df_size

"""## Shape of retrieved data
There are over 600,000 rows in the entire data set. I am only going to retrieve the relevant columns and relevant aggregation through the API call.

Columns retrieved:

borocode: 1 (Manhattan), 2 (Bronx), 3 (Brooklyn), 4 (Queens), 5 (Staten Island)
spc_common: specie name (132 unique species)
health: good, fair, poor
steward: Indicates the number of unique signs of stewardship observed for this tree (none, 1or2, 3or4, 4ormore)
Through trial and error, I determined that there is total of 4565 rows when data is grouped by borocode, spc_common, health, and steward. The limit value is set to 1000 since this is the maximum number of rows that can be retrieved through each API call. The offset value increments by 1000. max_row is set to 5000. This allows us to retrieve all 4565 rows.

NOTE: I had to use 'borocode' because I was getting error when I used the 'borough' column to group the data by.
"""

offset = 1000
max_row = 5000

for x in range(0, max_row, offset):
    #print('x is ' + str(x))
    soql_url = ('https://data.cityofnewyork.us/resource/nwxe-4ae8.json?$limit=1000&$offset=' + str(x) +\
        '&$select=borocode,spc_common,health,steward,count(tree_id)' +\
        '&$group=borocode,spc_common,health,steward').replace(' ', '%20')
    soql_trees = pd.read_json(soql_url)
    if(x==0):
        df = pd.DataFrame(columns=list(soql_trees.columns.values))
    df = df.append(soql_trees)

df = df.reset_index(drop=True)

"""Size of the dataset"""

len(df)

# unique names
len(list(df.spc_common.unique()))

# drop na to avoid errors in the visualization 
df = df.dropna(axis = 0, how = 'any')

df.head(5)

"""## Data preparation
Build a dash app for a arborist studying the health of various tree species (as defined by the variable ‘spc_common’) across each borough (defined by the variable ‘borough’). This arborist would like to answer the following two questions for each species and in each borough:

What proportion of trees are in good, fair, or poor health according to the ‘health’ variable?
Are stewards (steward activity measured by the ‘steward’ variable) having an impact on the health of trees?

## Work process

For every specice and in each borough, what proportion of trees are in good, fair, or poor health?

The application will allow arborist to select one specie, and the application will display proportion of trees that are in good, fair, or poor health across all boroughs. Arborist will be able to compare health of particular specie across all five boroughs.

Bar graphs will be used to present the proportions. The orientation of the bar graphs will be vertical. The bar graphs will be first grouped by boroughs for each health status.

The goal of the code below is to create a dataframe that has the columns: borocode, spc_common, health, ratio.

Ratio is the proportion of spc_common in the given borough that has the given heath level. For example, a ratio for red maple in Queens with a health of good is the proportion of good red maple trees in Queens.
"""

df_totals = df.groupby(['borocode', 'spc_common'])['count_tree_id'].sum()
df_total_by_borocode_specie_health = df.groupby(['borocode', 'spc_common', 'health'])['count_tree_id'].sum()

df_totals.head(5)

df_total_by_borocode_specie_health.head(5)

df_totals = df_totals.reset_index(drop=False)
df_total_by_borocode_specie_health = df_total_by_borocode_specie_health.reset_index(drop=False)

df_totals.head(5)

df_total_by_borocode_specie_health.head(5)

df_totals.columns = ['borocode', 'spc_common', 'total_for_specie_in_borough']
df_total_by_borocode_specie_health.columns = ['borocode', 'spc_common', 'health', 'total']

tree_proportions = pd.merge(df_total_by_borocode_specie_health, df_totals, on=['borocode', 'spc_common'])

tree_proportions.head(5)

tree_proportions['ratio'] = tree_proportions['total']/ tree_proportions['total_for_specie_in_borough']

tree_proportions.head(10)

"""## Question 2
I would like to use a scatter plot to represent the overall health status of the selected specie across all the boroughs. An overall health index is determined by assigning a numeric value to each health level (Poor=1, Fair=2, Good=3) and then calculating a weighted average for the selected specie for each borough. The overall health index score has a minimum score of 1 and a maximum score of 3.
"""

list(df['steward'].unique())

df.head(10)

df.sort_values(by=['borocode', 'spc_common', 'steward']).head(10)

df_total_by_steward = df.groupby(['borocode', 'spc_common', 'steward'])['count_tree_id'].sum()
df_total_by_steward = df_total_by_steward.reset_index(drop=False)
df_total_by_steward.columns = ['borocode', 'spc_common', 'steward', 'steward_total']
df_total_by_steward.head(10)

df_steward = pd.merge(df, df_total_by_steward, on=['borocode', 'spc_common', 'steward'])
df_steward.head(10)

di = {'Poor':1, 'Fair':2, 'Good':3}
df_steward['health_level'] = df_steward['health'].map(di)
df_steward.sort_values(by=['borocode', 'spc_common', 'steward']).head(10)
df_steward['health_index'] = (df_steward['count_tree_id']/df_steward['steward_total']) * df_steward['health_level']
df_steward.sort_values(by=['borocode', 'spc_common', 'steward']).head(10)
df_overall_health_index = df_steward.groupby(['borocode', 'spc_common', 'steward'])['health_index'].sum()
df_overall_health_index = df_overall_health_index.reset_index(drop=False)
df_overall_health_index.columns = ['borocode', 'spc_common', 'steward', 'overall_health_index']
di2 = {'3or4':3, '4orMore':4, 'None':1, '1or2':2}
df_overall_health_index['steward_level'] = df_overall_health_index['steward'].map(di2)
di3 = { 1:'Manhattan', 2:'Bronx', 3:'Brooklyn', 4:'Queens', 5:'Staten Island'}
df_overall_health_index['borough'] = df_overall_health_index['borocode'].map(di3)
df_overall_health_index['spc_common'] = df_overall_health_index['spc_common'].apply(lambda x: x.title())
df_overall_health_index.head(10)

